import { HockeyTechTeam } from "../team";

export default ([
  {
    id: "18",
    name: "Spartak",
    city: "Moscow",
    code: "SPR",
    nickname: "Spartak",
  },
  {
    id: "30",
    name: "Metallurg Mg",
    city: "Magnitogorsk",
    code: "MMG",
    nickname: "Metallurg Mg",
  },
  {
    id: "26",
    name: "Lokomotiv",
    city: "Yaroslavl",
    code: "LOK",
    nickname: "Lokomotiv",
  },
  {
    id: "44",
    name: "SKA",
    city: "Saint Petersburg",
    code: "SKA",
    nickname: "SKA",
  },
  {
    id: "8",
    name: "Dynamo Msk",
    city: "Moscow",
    code: "DYN",
    nickname: "Dynamo Msk",
  },
  {
    id: "10",
    name: "Avangard",
    city: "Omsk",
    code: "AVG",
    nickname: "Avangard",
  },
  {
    id: "32",
    name: "Salavat Yulaev",
    city: "Ufa",
    code: "SAL",
    nickname: "Salavat Yulaev",
  },
  {
    id: "56",
    name: "Avtomobilist",
    city: "Ekaterinburg",
    code: "AVT",
    nickname: "Avtomobilist",
  },
  {
    id: "105",
    name: "Lada",
    city: "Togliatti",
    code: "LAD",
    nickname: "Lada",
  },
  {
    id: "22",
    name: "Torpedo",
    city: "Nizhny Novgorod",
    code: "TOR",
    nickname: "Torpedo",
  },
  {
    id: "28",
    name: "Traktor",
    city: "Chelyabinsk",
    code: "TRK",
    nickname: "Traktor",
  },
  {
    id: "40",
    name: "Ak Bars",
    city: "Kazan",
    code: "AKB",
    nickname: "Ak Bars",
  },
  {
    id: "24",
    name: "Sibir",
    city: "Novosibirsk Region",
    code: "SIB",
    nickname: "Sibir",
  },
  {
    id: "16",
    name: "CSKA",
    city: "Moscow",
    code: "CSK",
    nickname: "CSKA",
  },
  {
    id: "42",
    name: "Severstal",
    city: "Cherepovets",
    code: "SEV",
    nickname: "Severstal",
  },
  {
    id: "12",
    name: "Amur",
    city: "Khabarovsk",
    code: "AMR",
    nickname: "Amur",
  },
  {
    id: "36",
    name: "Neftekhimik",
    city: "Nizhnekamsk",
    code: "NKH",
    nickname: "Neftekhimik",
  },
  {
    id: "38",
    name: "Dinamo Mn",
    city: "Minsk",
    code: "DMN",
    nickname: "Dinamo Mn",
  },
  {
    id: "46",
    name: "Barys",
    city: "Astana",
    code: "BAR",
    nickname: "Barys",
  },
  {
    id: "61",
    name: "Admiral",
    city: "Vladivostok",
    code: "ADM",
    nickname: "Admiral",
  },
  {
    id: "34",
    name: "Vityaz",
    city: "Moscow Region",
    code: "VIT",
    nickname: "Vityaz",
  },
  {
    id: "315",
    name: "Kunlun RS",
    city: "Beijing",
    code: "KRS",
    nickname: "Kunlun RS",
  },
  {
    id: "113",
    name: "HC Sochi",
    city: "Sochi",
    code: "SCH",
    nickname: "HC Sochi",
  },
] satisfies HockeyTechTeam[]);
