import type { HockeyTechTeam } from "../team";

export default [
  {
    id: "375",
    name: "Omskie Yastreby",
    city: "Omsk",
    code: "OMS",
    nickname: "Omskie Yastreby",
  },
  {
    id: "455",
    name: "JHC Spartak",
    city: "Moscow",
    code: "SPR",
    nickname: "Spartak",
  },
  {
    id: "625",
    name: "Irbis",
    city: "Kazan",
    code: "IRB",
    nickname: "Irbis",
  },
  {
    id: "443",
    name: "Krasnaya Armiya",
    city: "Moscow",
    code: "ARM",
    nickname: "Krasnaya Armiya",
  },
  {
    id: "395",
    name: "Tolpar",
    city: "Ufa",
    code: "TOL",
    nickname: "Tolpar",
  },
  {
    id: "711",
    name: "Dinamo-Shinnik",
    city: "Bobruysk",
    code: "DNS",
    nickname: "Dinamo-Shinnik",
  },
  {
    id: "669",
    name: "Loko-76",
    city: "Yaroslavl",
    code: "L76",
    nickname: "Loko-76",
  },
  {
    id: "371",
    name: "Mamonty Ugry",
    city: "Khanty-Mansiysk",
    code: "MAM",
    nickname: "Mamonty Ugry",
  },
  {
    id: "383",
    name: "Belye Medvedi",
    city: "Chelyabinsk",
    code: "BEL",
    nickname: "Belye Medvedi",
  },
  {
    id: "657",
    name: "Mikhailov Academy",
    city: "Tulskiy Region",
    code: "MIK",
    nickname: "Mikhailov Academy",
  },
  {
    id: "629",
    name: "Krylya Sovetov",
    city: "Moscow",
    code: "SOV",
    nickname: "Krylya Sovetov",
  },
  {
    id: "415",
    name: "Ladya",
    city: "Togliatti",
    code: "LAD",
    nickname: "Ladya",
  },
  {
    id: "347",
    name: "Loko",
    city: "Yaroslavl",
    code: "LOK",
    nickname: "Loko",
  },
  {
    id: "427",
    name: "SKA-1946",
    city: "Saint Petersburg",
    code: "SKA",
    nickname: "SKA-1946",
  },
  {
    id: "355",
    name: "Stalnye Lisy",
    city: "Magnitogorsk",
    code: "STA",
    nickname: "Stalnye Lisy",
  },
  {
    id: "351",
    name: "Chaika",
    city: "Nizhny Novgorod",
    code: "CHA",
    nickname: "Chaika",
  },
  {
    id: "387",
    name: "Avto",
    city: "Yekaterinburg",
    code: "AVT",
    nickname: "Avto",
  },
  {
    id: "439",
    name: "JHC Dynamo M",
    city: "Balashikha",
    code: "DYM",
    nickname: "Dynamo M",
  },
  {
    id: "391",
    name: "Reaktor",
    city: "Nizhnekamsk",
    code: "REA",
    nickname: "Reaktor",
  },
  {
    id: "447",
    name: "JHC Dynamo SPb",
    city: "Saint Petersburg",
    code: "DYS",
    nickname: "Dynamo SPb",
  },
  {
    id: "467",
    name: "Russkie Vityazi",
    city: "Chekhov",
    code: "VIT",
    nickname: "Russkie Vityazi",
  },
  {
    id: "673",
    name: "Molot",
    city: "Perm",
    code: "MOL",
    nickname: "Molot",
  },
  {
    id: "359",
    name: "Snezhnye Barsy",
    city: "Astana",
    code: "SZN",
    nickname: "Snezhnye Barsy",
  },
  {
    id: "411",
    name: "Kuznetskie Medvedi",
    city: "Novokuznetsk",
    code: "KUZ",
    nickname: "Kuznetskie Medvedi",
  },
  {
    id: "435",
    name: "Almaz",
    city: "Cherepovets",
    code: "ALM",
    nickname: "Almaz",
  },
  {
    id: "423",
    name: "Amurskie Tigry",
    city: "Khabarovsk",
    code: "AMR",
    nickname: "Amurskie Tigry",
  },
  {
    id: "699",
    name: "Krasnoyarskie Rysi",
    city: "Krasnoyarsk",
    code: "RYS",
    nickname: "Krasnoyarskie Rysi",
  },
  {
    id: "459",
    name: "JHC Atlant",
    city: "Moscow Region",
    code: "ATL",
    nickname: "Atlant",
  },
  {
    id: "633",
    name: "Sakhalinskie Akuly",
    city: "Sakhalin Region",
    code: "SAK",
    nickname: "Sakhalinskie Akuly",
  },
  {
    id: "431",
    name: "Typhoon",
    city: "Primorsky Krai",
    code: "TFN",
    nickname: "Typhoon",
  },
  {
    id: "379",
    name: "Tyumensky Legion",
    city: "Tyumen",
    code: "TYL",
    nickname: "Tyumensky Legion",
  },
  {
    id: "707",
    name: "AKM-Junior",
    city: "Tula region",
    code: "AKM",
    nickname: "AKM-Junior",
  },
  {
    id: "545",
    name: "HC Kapitan",
    city: "Stupino",
    code: "KAP",
    nickname: "HC Kapitan",
  },
  {
    id: "581",
    name: "SKA-Junior",
    city: "Leningrad Region",
    code: "SKJ",
    nickname: "SKA-Junior",
  },
  {
    id: "621",
    name: "Sibirskie Snaipery",
    city: "Novosibirisk",
    code: "SIB",
    nickname: "Sibirskie Snaipery",
  },
  {
    id: "399",
    name: "Sputnik",
    city: "Almetyevsk",
    code: "SPT",
    nickname: "Sputnik",
  },
  {
    id: "703",
    name: "Khors-Kareliya",
    city: "Kondopoga",
    code: "KRS",
    nickname: "Khors-Kareliya",
  },
  {
    id: "851",
    name: "AKM-Novomoskovsk",
    city: "Novomoskovsk",
    code: "AKN",
    nickname: "AKM-Novomoskovsk",
  },
] satisfies HockeyTechTeam[];
